services:
  #  wilayah-indo-app:
  #    image: 'hendisantika/wilayah-indo-app:0.0.1'
  #    build:
  #      context: .
  #    container_name: wilayah-indo-app
  #    ports:
  #      - "8080:8080"
  #    restart: always
  #    depends_on:
  #      - db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wilayah-indo-app
  #      - SPRING_DATASOURCE_USERNAME=hendisantika
  #      - SPRING_DATASOURCE_PASSWORD=hendi
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:17.5-alpine3.21'
    container_name: db
    environment:
      - POSTGRES_DB=wilayah_indonesia
      - POSTGRES_USER=yu71
      - POSTGRES_PASSWORD=53cret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
